allow eviction of DEFAULT template cache - this leaks memory, JVM get OOM fast if the expressions are big.
querydsl/querydsl pull request #2218
Opened 2017-11-05 12:29 UTC by s50600822

TemplateFactory.cache leaks memory, JVM get OOM fast if the expressions are big.
Provide methods to clearCache optionally.

2017-11-05 12:49 UTC, Shredder121 commented
:+1:
I'm not opposed to the idea.
However could you explain a little on how the cache could keep growing?
Maybe there's something else we also need to address first?

2017-11-08 01:38 UTC, karahatherly commented
> However could you explain a little on how the cache could keep growing?

`TemplateFactory.cache` is a `ConcurrentHashMap` so its size is bound only by the number of cache misses. On a project which uses querydsl like Jira does this can result in OOMEs as @s50600822 states. Exposing methods to clear it allows us to

> Maybe there's something else we also need to address first?

I think additionally we should change the `ConcurrentHashMap` to a guava cache and configure it at run-time based on a `CacheBuilderSpec` representation in a property, to allow querydsl consumers to tune that cache if necessary. We'd then still want to expose the `invalidate*` and `cleanUp` methods from `Cache`, similar to what's done in this PR for the `Map`.

2018-01-07 09:58 UTC, timowest commented
I'd also like to see a use case description first, how this cache could grow too big. There should be finite amount of operation serialization templates in a project.

2018-04-05 16:26 UTC, s50600822 commented
It was just a matter of scale. Apparently there is a platform that heavily relies on user inputs and context to build queries to database. 
Adopting serverless architecture of that platform forces the JVMs to serve request from all different customers with different contexts since there's no sticky session.
(that wasn't my idea btw :< ).

2018-04-05 16:27 UTC, Shredder121 commented
Could you elaborate on the scale? Is it arbitrary amounts of applications in one JVM?

2018-07-17 07:10 UTC, dodolzg commented
I have the same problem, java.lang.OutOfMemoryError.
JVM shows that there are lots of char[], string which refrence sql template, however it can be reached by GC ROOT.

2018-10-10 00:38 UTC, s50600822 commented
> Could you elaborate on the scale? Is it arbitrary amounts of applications in one JVM?

put it this way if you can't think of how big the mem leak is, how about a limit it will never use up says 20MB or something ? The code that generate that many query String into the cache probably need to be fixed, but the library could also help limiting the blast radious.

2018-10-19 02:08 UTC, s50600822 commented
@Shredder121 do you want to merge it, I don't have write access.

2020-05-28 16:14 UTC, jwgmeligmeyling commented
Wouldn't a `Collections.synchronizedMap(new WeakHashMap<String, Template>());` be more appropiate here?

It seems this cache is mostly here to reuse frequently used `Template` instances among operators. Because these are mostly defined in singleton instances (Templates), these are constantly in memory anyway.

Some voices are raising to slowly migrate off from Guava: #2324

2020-10-26 20:59 UTC, jwgmeligmeyling requested changes
Please don't merge this yet, I am working on this patch for the 5.x release.

2020-12-31 18:43 UTC, closed without merging