Add class cast in case entity is generic
querydsl/querydsl pull request #2526
Opened 2020-02-11 14:39 UTC by IlyaNerd

Hello. This cast is required by compiler in case entity is generic. I understand that generating from database cant have generic entities, but we have our own code generation module on top of sql one, which generates Q classes for sql from jpa annotations. EntitySerializer has this class cast - sql one doesn't.

2020-05-28 14:02 UTC, johnktims commented
Thanks @IlyaNerd.  Please add a test and rebase on `master`.

2020-06-07 13:58 UTC, IlyaNerd commented
@johnktims hey, im not sure how this scenario can be auto tested. sql apt generates classes from tables and classes are named from tables, so there is no way you can get generic class there. But in my scenario we have our own sql apt which generates classes from jpa annotations (mb should create a pr for such feature) just like querydsl-jpa-codegen, and this cast is taken from there as we can get generic class there.
So unless i somehow add params to creating simple type in `com.querydsl.sql.codegen.MetaDataExporter#createEntityType` i dont see a way to generate generic class.
Please advice, if you have an idea how i can write a test case, thanks.

2020-10-27 19:24 UTC, jwgmeligmeyling commented
Do you have an example @IlyaNerd ? Then I can create the test for you.

2021-06-02 07:48 UTC, jwgmeligmeyling requested changes
Test missing.

2022-06-14 23:46 UTC, closed without merging