[#2380] Added configuration for gradle incremental annotation processing
querydsl/querydsl pull request #2636
Opened 2020-08-13 07:20 UTC by ebbing

We are using this change for six months in a quite big project and it works fine for us.

2020-08-13 07:52 UTC, natros commented
that's only for JPA

2020-08-13 12:18 UTC, ebbing commented
that's right

Am Do., 13. Aug. 2020 um 09:52 Uhr schrieb Filipe Sousa <
notifications@github.com>:

> that's only for JPA
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/querydsl/querydsl/pull/2636#issuecomment-673322528>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGCKFJMSXY6FX7NWSFLRGDSAOLUZANCNFSM4P56IQUQ>
> .
>

2020-09-02 15:04 UTC, miensol commented
@idosal @johnktims @pslootweg @robertandrewbain @Shredder121 @timowest Any chance you'll have a time to review the changes?

2020-09-02 16:00 UTC, jwgmeligmeyling commented
Many of our contributors are not Gradle experts. I see concerns that this only works for JPA. I have no confirmation that it will still generate code for SQL or any of our other packages at all.

For this to be integrated, we need test cases or at least some sort of proof that everything still works. And not just for JPA, but also the other packages. Currently we don't build with gradle.

As it is, this PR is unacceptable IMO.

2020-09-02 16:01 UTC, jwgmeligmeyling requested changes
Needs test

2020-09-02 16:24 UTC, natros commented
Mapstruct enabled annotation incremental compilation and they were able to test with maven using gradle-test-kit and gradle-tooling-api. 

https://github.com/mapstruct/mapstruct/blob/master/integrationtest/src/test/java/org/mapstruct/itest/tests/GradleIncrementalCompilationTest.java

2020-09-02 19:38 UTC, miensol commented
@jwgmeligmeyling Would you mind sharing the reasons why you would prefer having the gradle annotation processing cache enabled for other processors?

I might be missing something so please clarify. Releasing this change, assuming it is tested properly, would improve the experience for gradle + jpa users. It would not harm SQL users.

2020-09-03 11:25 UTC, jwgmeligmeyling commented
> Would you mind sharing the reasons why you would prefer having the gradle annotation processing cache enabled for other processors?

I don't.

@natros pointed out that this only fixes the issue for JPA. The module in which this file is created, also supports JDO, JPA, Morphia and Spring Roo. I want to make sure that with these change these metamodels are not affected. It would be great if these generators also supported incremental annotation processing, but my goal here really is that they keep working and that JPA metamodel generation is not unintentionally triggered for projects that do not want to use QueryDSL JPA.

If there are tests or some example project that shows that both SQL and JPA metamodel generation just works fine with the change applied, thats enough for me. But as a non-gradle user, I need some example to verify this change.

2020-09-19 12:53 UTC, NicklasWallgren commented
@ebbing Have you made the artifact of this PR available somewhere? I'm eager to try it out.

2021-01-24 15:41 UTC, merged