Switch from Slf4j to JUL to reduce transitive dependencies
querydsl/querydsl pull request #2711
Opened 2021-01-01 23:32 UTC by jwgmeligmeyling

I am not entirely decided on this patch yet.

Yes, users _often_ have and want Slf4j for better performance and configurability. Most applications will have or will want to have some implementation of Slf4j on their classpath anyway.

However, what if QueryDSL is the only dependency bringing a dependency to Slf4j? And forcing projects to adapt to Slf4j?

In the same spirit of the removal of Guava, JSR305, etc. it would be nice to decrease the number of dependencies forced on our users to an absolute minimum. JUL is included in the JRE (since 1.4) and can easily be bridged to Slf4j should users so desire.

Furthermore, we don't really need the performance anyway. We log very seldomly. We never use variable substitution in log statements. We mostly log when executing a query, in which case the latency of the log statement will be negligable compared to the roundtrip of the query anyways.

2021-01-02 00:29 UTC, jwgmeligmeyling commented
@johnktims @robertandrewbain @Shredder121 @idosal Would love to have some feedback on this

2021-01-02 20:44 UTC, robertandrewbain requested changes
All looks good to me, other than remaining references to slf4j in the poms and when running mvn dependency:tree

2021-01-03 15:42 UTC, jwgmeligmeyling commented
- `querydsl-core` has no dependency to slf4j anymore
- `querydsl-jpa` only has a `test` scoped dependency transively through `batoo-jpa` (seems allright)
- `querydsl-sql` only has a `test` scoped dependency transively through `querydsl-spatial` (seems allright)
- `querydsl-spatial` has a `compile` type scoped dependency on slf4j, through `geolatte`. As it does not declare a direct dependency on `geolatte`, would `geolatte` be replaced with a version not itself dependent on slf4j, the transitive dependency on slf4j would dissapear.

Bottom line: if Geolatte is on the classpath, we need `slf4j` on there as well. If Geolatte is included, slf4j will be excluded because its only included transitively through Geolatte (through Querydsl Spatial).

So I guess this is actually fine😉 

```
"C:\Program Files\Java\jdk1.8.0_211\bin\java.exe" -Dmaven.multiModuleProjectDirectory=C:\Users\Jan-Willem\git\querydsl "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\lib\idea_rt.jar=62015:C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2020.3 compile dependency:tree
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Querydsl                                                           [pom]
[INFO] Querydsl - Core module                                             [jar]
[INFO] Querydsl - Codegen utils                                           [jar]
[INFO] Querydsl - Codegen module                                          [jar]
[INFO] Querydsl - APT support                                             [jar]
[INFO] Querydsl - Spatial module                                          [jar]
[INFO] Querydsl - Collections support                                     [jar]
[INFO] Querydsl - SQL support                                             [jar]
[INFO] Querydsl - SQL Spatial support                                     [jar]
[INFO] Querydsl - SQL codegen support                                     [jar]
[INFO] Querydsl - SQL Spring support                                      [jar]
[INFO] Querydsl - Maven plugin                                   [maven-plugin]
[INFO] Querydsl - JPA support                                             [jar]
[INFO] Querydsl - JPA Codegen support                                     [jar]
[INFO] Querydsl - JDO support                                             [jar]
[INFO] Querydsl - Lucene 3 support                                        [jar]
[INFO] Querydsl - Lucene 4 support                                        [jar]
[INFO] Querydsl - Lucene 5 support                                        [jar]
[INFO] Querydsl - Hibernate Search support                                [jar]
[INFO] Querydsl - Mongodb support                                         [jar]
[INFO] Querydsl - Scala support                                           [jar]
[INFO] querydsl-kotlin                                                    [jar]
[INFO] 
[INFO] ---------------------< com.querydsl:querydsl-root >---------------------
[INFO] Building Querydsl 5.0.0-SNAPSHOT                                  [1/22]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ querydsl-root ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:check (checkstyle) @ querydsl-root ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:check (checkstyle-main) @ querydsl-root ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (prepare-agent) @ querydsl-root ---
[INFO] argLine set to -javaagent:C:\\Users\\Jan-Willem\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.5.201505241946\\org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=C:\\Users\\Jan-Willem\\git\\querydsl\\target\\jacoco.exec -Xms256m -Xmx512m
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ querydsl-root ---
[INFO] com.querydsl:querydsl-root:pom:5.0.0-SNAPSHOT
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] +- org.easymock:easymock:jar:3.0:test
[INFO] |  \- org.objenesis:objenesis:jar:1.2:test
[INFO] +- org.reflections:reflections:jar:0.9.12:test
[INFO] |  \- org.javassist:javassist:jar:3.26.0-GA:test
[INFO] \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.18:compile
[INFO] 
[INFO] ---------------------< com.querydsl:querydsl-core >---------------------
[INFO] Building Querydsl - Core module 5.0.0-SNAPSHOT                    [2/22]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ querydsl-core ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:check (checkstyle) @ querydsl-core ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:check (checkstyle-main) @ querydsl-core ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (prepare-agent) @ querydsl-core ---
[INFO] argLine set to -javaagent:C:\\Users\\Jan-Willem\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.5.201505241946\\org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=C:\\Users\\Jan-Willem\\git\\querydsl\\querydsl-core\\target\\jacoco.exec -Xms256m -Xmx512m
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ querydsl-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Jan-Willem\git\querydsl\querydsl-core\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ querydsl-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 237 source files to C:\Users\Jan-Willem\git\querydsl\querydsl-core\target\classes
[INFO] /C:/Users/Jan-Willem/git/querydsl/querydsl-core/src/main/java/com/querydsl/core/types/Template.java: Some input files use unchecked or unsafe operations.
[INFO] /C:/Users/Jan-Willem/git/querydsl/querydsl-core/src/main/java/com/querydsl/core/types/Template.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ querydsl-core ---
[INFO] com.querydsl:querydsl-core:jar:5.0.0-SNAPSHOT
[INFO] +- org.jetbrains:annotations:jar:20.1.0:provided
[INFO] +- com.mysema.commons:mysema-commons-lang:jar:0.2.4:compile
[INFO] +- cglib:cglib:jar:3.3.0:compile
[INFO] |  \- org.ow2.asm:asm:jar:7.1:compile
[INFO] +- org.jvnet.hudson:annotation-indexer:jar:1.2:compile
[INFO] +- jdepend:jdepend:jar:2.9.1:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] +- org.easymock:easymock:jar:3.0:test
[INFO] |  \- org.objenesis:objenesis:jar:1.2:test
[INFO] +- org.reflections:reflections:jar:0.9.12:test
[INFO] |  \- org.javassist:javassist:jar:3.26.0-GA:test
[INFO] \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.18:compile
[INFO] 
[INFO] ---------------------< com.querydsl:codegen-utils >---------------------
[INFO] Building Querydsl - Codegen utils 5.0.0-SNAPSHOT                  [3/22]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ codegen-utils ---
[INFO] 
[INFO] --- maven-checkst [...]

2021-01-03 15:44 UTC, jwgmeligmeyling commented on pom.xml
> +      <dependency>
As @robertandrewbain mentioned these managed dependencies can now be removed from the parent pom, as the child poms don't refer to it anymore.

2021-01-18 21:44 UTC, merged